destination: ./_site
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
headline:    computers, programming, ponies and snakes.
url:         http://www.tomaz.me
domain:      www.tomaz.me
exclude: ['README.MD', 'sitemap.xml']

tag_page_layout: tag_page
tag_page_dir: tags

asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  #display_path: nil       # Default = nil
  gzip: true # Default = false
